# ADGM Corporate Agent Configuration
app:
  name: "ADGM Corporate Document Review Agent"
  version: "1.0.0"
  
llm:
  provider: "openai"
  model: "gpt-4"
  temperature: 0.1
  max_tokens: 2000
  
vector_db:
  provider: "chromadb"
  collection_name: "adgm_regulations"
  embedding_model: "text-embedding-ada-002"
  
document_processing:
  chunk_size: 1000
  chunk_overlap: 200
  max_file_size_mb: 10
  
compliance:
  adgm_sources:
    - "ADGM Companies Regulations 2020"
    - "ADGM Commercial Licensing Regulations"
    - "ADGM Employment Law"
    - "ADGM Data Protection Regulations"
